### ISSUE TITLE
jasmine.any isn't working with these matchers

### ISSUE THREAD

**Issue by hayesmaker** [AdamNowotny/jasmine-signals#6]
Why would this test fail?

var spy = spyOnSignal(controller.initialCardsDealt);
            controller.initialCardsDealt.dispatch([], []);
         expect(spy).toHaveBeenDispatchedWith(jasmine.any[Object],jasmine.any[Object]);

Fails:

Expected [Signal active:true numListeners:1] to have been dispatched with (,) but was with (,)
Error: Expected [Signal active:true numListeners:1] to have been dispatched with (,) but was with (,)
    at new jasmine.ExpectationResult (http://localhost:63342/solitaire-showdown/public/js/test/jasmine/lib/jasmine/jasmine.js:114:32)
    at null.toHaveBeenDispatchedWith (http://localhost:63342/solitaire-showdown/public/js/test/jasmine/lib/jasmine/jasmine.js:1235:29)
    at null.<anonymous> (http://localhost:63342/solitaire-showdown/public/js/test/jasmine/spec/hayesmaker/solitaire/game/components/rulesSpec.js:48:25)
    at jasmine.Block.execute (http://localhost:63342/solitaire-showdown/public/js/test/jasmine/lib/jasmine/jasmine.js:1064:17)
    at jasmine.Queue.next_ (http://localhost:63342/solitaire-showdown/public/js/test/jasmine/lib/jasmine/jasmine.js:2096:31)
    at jasmine.Queue.start (http://localhost:63342/solitaire-showdown/public/js/test/jasmine/lib/jasmine/jasmine.js:2049:8)
    at jasmine.Spec.execute (http://localhost:63342/solitaire-showdown/public/js/test/jasmine/lib/jasmine/jasmine.js:2376:14)
    at jasmine.Queue.next_ (http://localhost:63342/solitaire-showdown/public/js/test/jasmine/lib/jasmine/jasmine.js:2096:31)
    at jasmine.Queue.start (http://localhost:63342/solitaire-showdown/public/js/test/jasmine/lib/jasmine/jasmine.js:2049:8)
    at jasmine.Suite.execute (http://localhost:63342/solitaire-showdown/public/js/test/jasmine/lib/jasmine/jasmine.js:2521:14)

**Comment by r4j4h** [comment]
Seconding this, the matchers work great except do not support jasmine.any. I have not looked into seeing what it would take to support it, but I do not imagine it should be much.

**Comment by r4j4h** [comment]
So looking into it it should be pretty easy from http://jasmine.github.io/2.1/custom_matcher.html.
line 75 `        toHaveBeenDispatchedWith: function () {` needs to become `function(util, customEqualityTesters) {`

and pass that through to `util.equals` instead of `paramsMatch`. The problem right now is that that call is hidden behind a `.map` call to populate `results.pass`.

This is not my current goal so I am not pursuing this further at this moment, but instead am using the following alternative:

Use toHaveBeenDispatched, as Adam mentioned, and then to actually do the check, inspect your signal spy. In my case that looks like this:

`mySignalSpy.dispatches[0]` is the array of arguments given to the first dispatch. Check that array for only the values you are interested in. :)

**Comment by AdamNowotny** [comment]
Just added a test for jasmine.any and seems to work fine with the latest code:

```
it('supports jasmine.any', function () {
    signal.dispatch('some string', {foo: 'bar'});
    expect(spy).toHaveBeenDispatchedWith(jasmine.any(String),jasmine.any(Object));
});
```

Looking at your example I think jasmine.any[Object] is undefined and should be jasmine.any(Object)
